[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'cd server && npm ci',
  'npm ci'
]

[phases.build]
cmds = [
  'npm run build',
  'cd server && npm run migrate'
]

[start]
cmd = 'cd server && npm start'