[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
  'npm run build',
  'cd server && npm install',
  'cd server && npm run migrate'
]

[start]
cmd = 'cd server && npm start'